method: adamimic
environment:
  task: largebox_plane
  device: cuda:0
  num_envs: 8192
  sim_dt: 0.02
  decimation: 4
  fix_root_link: false
  startup_randomization: true
  max_episode_steps: 500
  motion_start_phase: 0
  motion_end_phase: -1
  reset_noise: true
  interval_pushes: true
  observation_noise: true
  reset_phase_sampling: zero
  rsi_keyframe_count: 21
  adaptive_motion_sampling: false
  adaptive_num_bins: 0
  adaptive_alpha: 0.001
  adaptive_predecessor_ratio: 0.8
  adaptive_predecessor_lookback_bins: 1
  action_rate_weight: 0.1

parameters:
  stage: stage2
  actor_hidden_dims: [512, 256, 128]
  critic_hidden_dims: [512, 256, 128]
  activation: elu
  rollout_env_steps: 75
  discount_gamma: 0.99
  time_discount_gamma: 1.0
  gae_lambda: 0.95
  clip_range: 0.2
  desired_kl: 0.001
  policy_epochs: 5
  num_mini_batches: 4
  micro_batch_size: 4096
  value_loss_coef: 1.0
  entropy_coef: 0.01
  policy_lr: 0.001
  weight_decay: 0.01
  empirical_normalization: true
  init_at_random_ep_len: true
  max_grad_norm: 1.0
  use_clipped_value_loss: true

  infer_keyframe_time: true
  actor_time_scale_range: [-0.015, 0.02]
  fixed_dt: 0.02
  time_min_std: 0.005
  init_noise_std: 0.08
  train_time: true
  time_reward_scale: 1.0
  use_timeout_bootstrap: true

  use_smooth: false
  smoothness_upper_bound: 1.0
  smoothness_lower_bound: 0.1
  value_smoothness_coef: 0.1

  residual_delta: true
  checkpoint_path: ../runs/adamimic_stage1_largebox/checkpoints/last.pt
  freeze_base: true
  residual_time_threshold: 0.0

training:
  seed: 1
  max_updates: 500
  log_every: 10
  save_every: 50
  resume: ""
  reset_optimizer_on_resume: false
  reset_sampler_on_resume: false
  validation_every: 50
  validation_max_steps: 500
  validation_start_phase: 0
  validation_directional_start_phase: -1
  validation_fixed_seed: 1
  validation_done_frac_early_stop: 0.98
  target_validation_steps: 0
