algorithm: reinflow
environment:
  task: largebox_plane
  device: cuda:0
  num_envs: 8192
  sim_dt: 0.02
  decimation: 4
  fix_root_link: false
  startup_randomization: true
  max_episode_steps: 500
  motion_start_phase: 0
  motion_end_phase: -1
  reset_noise: true
  interval_pushes: true
  observation_noise: true
  adaptive_motion_sampling: true
  adaptive_num_bins: 0
  adaptive_alpha: 0.001
  adaptive_predecessor_ratio: 0.8
  adaptive_predecessor_lookback_bins: 1
  action_rate_weight: 0.1
parameters:
  horizon: 4
  actor_hidden_dims: [512, 256, 128]
  noise_hidden_dims: [64, 64]
  critic_hidden_dims: [512, 256, 128]
  activation: mish
  flow_steps: 4
  timestep_embed_dim: 8
  action_scale: 1.0
  min_denoising_std: 0.10
  max_denoising_std: 0.24
  randn_clip_value: 3.0
  logprob_min: -1.0
  logprob_max: 1.0
  account_for_initial_stochasticity: true
  normalize_denoising_horizon: true
  normalize_action_dimension: true
  rollout_env_steps: 24
  discount_gamma: 0.99
  gae_lambda: 0.95
  clip_range: 0.01
  target_kl: 0.01
  policy_epochs: 5
  num_mini_batches: 4
  entropy_coef: 0.03
  value_loss_coef: 1.0
  policy_lr: 0.000045
  value_lr: 0.00065
  weight_decay: 0.0
  critic_weight_decay: 0.00001
  empirical_normalization: true
  init_at_random_ep_len: true
  max_grad_norm: 1.0
  pretrained_actor_path: ""
training:
  seed: 0
  max_updates: 1000
  log_every: 10
  save_every: 100
  resume: ""
  reset_optimizer_on_resume: false
  reset_sampler_on_resume: false
  validation_every: 100
  validation_max_steps: 500
  validation_start_phase: 0
  validation_directional_start_phase: -1
  validation_fixed_seed: -1
  validation_done_frac_early_stop: 0.98
  target_validation_steps: 0
